version: '3.1'

services:
  db:
    ports:
      - '3306:3306'
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: aboba

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
